params:  
  diff_env:
    name: HumanoidEnv
    stochastic_env: True
    episode_length: 1000
    MM_caching_frequency: 48 
  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:

    mlp:
      units: [512, 256]
      activation: relu
      initializer:
        name: default

    log_std_bounds: [-5, 2]

  load_checkpoint: False
  load_path: nn/humanoid.pth

  config:
    name: 'Humanoid_SAC'
    env_name: dflex
    normalize_input: True
    reward_shaper:
      scale_value: 1
    device: cuda
    max_epochs: 1500
    num_steps_per_episode: 128
    save_best_after: 100
    save_frequency: 10000
    gamma: 0.99
    init_alpha: 1
    alpha_lr: 0.0002
    actor_lr: 0.0003
    critic_lr: 0.0003
    critic_tau: 0.005
    batch_size: 2048
    learnable_temperature: true
    num_seed_steps: 2
    replay_buffer_size: 1000000
    num_actors: 64

    env_config:
      env_name: 'humanoid'